[project]
name = "maze-solver"

[tool.pyside6-project]
files = [
    "main.py",

    "viewmodel/maze_viewmodel.py",

    "view/App/AlgorithmSelector.qml",
    "view/App/ConfigurationArea.qml",
    "view/App/ContentArea.qml",
    "view/App/Main.qml",
    "view/App/MazeCell.qml",
    "view/App/MazeContainer.qml",
    "view/App/MazeGrid.qml",
    "view/App/MazeWrapper.qml",
    "view/App/FlowPanel.qml",
    "view/App/PathCell.qml",
    "view/App/PathGrid.qml",
    "view/App/qmldir",
    "view/App/SideBar.qml",
    "view/App/SideBarButton.qml",
    "view/App/SimulationButton.qml",
    "view/Style/Colors.qml",
    "view/Style/qmldir"
]

[tool.pyright]
pythonVersion = "3.14"
pythonPath = "C:/Python314/python.exe"
reportMissingImports = "none"
reportMissingModuleSource = "none"
extraPaths = [
    "C:/Users/Brando WhiteNoise/AppData/Roaming/Python/Python314/site-packages",
    "C:/Python314/Lib/site-packages"
]

[tool.pyrefly]
site-packages = [
    "C:/Users/Brando WhiteNoise/AppData/Roaming/Python/Python314/site-packages",
    "C:/Python314/Lib/site-packages"
]